# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"W\n\x13registerUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\r\n\x05\x61\x64min\x18\x04 \x01(\x08\"6\n\x14registerUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t2M\n\x0cUserServices\x12=\n\x0cRegisterUser\x12\x14.registerUserRequest\x1a\x15.registerUserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERUSERREQUEST']._serialized_start=14
  _globals['_REGISTERUSERREQUEST']._serialized_end=101
  _globals['_REGISTERUSERRESPONSE']._serialized_start=103
  _globals['_REGISTERUSERRESPONSE']._serialized_end=157
  _globals['_USERSERVICES']._serialized_start=159
  _globals['_USERSERVICES']._serialized_end=236
# @@protoc_insertion_point(module_scope)
